# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAjhKo-5mVf0s_D8YzBXTXaGch1oah4H
"""

!pip install streamlit

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# ---------------------------
# Monte Carlo Simulation
# ---------------------------
def run_simulation(
    sea_level_rise,
    extreme_weather_freq,
    infrastructure_resilience,
    digital_dependency,
    adaptation_investment,
    n_simulations=10000
):
    results = []

    for _ in range(n_simulations):
        sea_level = np.random.normal(sea_level_rise, 0.1)
        weather = np.random.normal(extreme_weather_freq, 0.05)

        sea_level = max(sea_level, 0)
        weather = min(max(weather, 0), 1)

        risk = (
            sea_level *
            weather *
            digital_dependency *
            (1 - infrastructure_resilience) *
            (1 - adaptation_investment)
        )

        results.append(risk)

    return np.array(results)

# ---------------------------
# Streamlit UI
# ---------------------------
st.set_page_config(page_title="Strategic Foresight Simulator", layout="centered")

st.title("Strategic Foresight Simulator")
st.subheader("UN 2.0 – Scenario-Based Risk Exploration")

st.markdown(
"""
This tool explores **future risks to coastal digital infrastructure**
under uncertainty.
It uses **Monte Carlo simulation** to support **anticipatory governance**.

⚠️ Results show **probabilities, not predictions**.
"""
)

# Sidebar inputs
st.sidebar.header("Scenario Parameters")

sea_level_rise = st.sidebar.slider(
    "Sea Level Rise (meters)", 0.0, 2.0, 0.5, 0.1
)

extreme_weather_freq = st.sidebar.slider(
    "Extreme Weather Frequency", 0.0, 1.0, 0.3, 0.05
)

infrastructure_resilience = st.sidebar.slider(
    "Infrastructure Resilience", 0.0, 1.0, 0.6, 0.05
)

digital_dependency = st.sidebar.slider(
    "Digital Dependency", 0.0, 1.0, 0.7, 0.05
)

adaptation_investment = st.sidebar.slider(
    "Adaptation Investment", 0.0, 1.0, 0.4, 0.05
)

# Run simulation
results = run_simulation(
    sea_level_rise,
    extreme_weather_freq,
    infrastructure_resilience,
    digital_dependency,
    adaptation_investment
)

# Summary metrics
st.subheader("Risk Summary")

st.write("**Mean Risk:**", round(results.mean(), 4))
st.write("**Worst Case (95th percentile):**", round(np.percentile(results, 95), 4))
st.write("**Best Case (5th percentile):**", round(np.percentile(results, 5), 4))

# Plot
fig, ax = plt.subplots()
ax.hist(results, bins=50)
ax.set_xlabel("Digital Service Disruption Risk")
ax.set_ylabel("Frequency")
ax.set_title("Risk Distribution Under Uncertainty")

st.pyplot(fig)

# Policy context
st.markdown("---")
st.subheader("Policy Relevance")

st.markdown(
"""
This simulator can support:
- Early risk awareness
- Infrastructure investment prioritization
- Climate adaptation planning

It is designed to **complement**, not replace, human decision-making.
"""
)

st.subheader("Ethical & Responsible Use")

st.markdown(
"""
- Simplified model for educational purposes
- Uses assumed parameters
- Should not be used as a sole decision-making tool
"""
)

!streamlit run app.py

!pip install streamlit pyngrok

from pyngrok import ngrok

public_url = ngrok.connect(8501)
print("Streamlit URL:", public_url)